version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=department
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d department"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: unless-stopped
    container_name: core
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: department
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    

volumes:
  postgres_data: